module.exports = {
  // --- OAuth/Token Errors (Giữ lại) ---
  BAD_OAUTH_STATE: 'BAD_OAUTH_STATE',
  PROVIDER_MISMATCH: 'PROVIDER_MISMATCH',
  AUTH_MISSING_REFRESH_TOKEN: 'AUTH_MISSING_REFRESH_TOKEN',
  AUTH_INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_MISSING_ACCESS_TOKEN: 'AUTH_MISSING_ACCESS_TOKEN',
  AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  TOKEN_GENERATION_FAILED: 'TOKEN_GENERATION_FAILED',

  // --- Hành động Bổ sung (Status Code 202) ---
  REQUIRE_PHONE_USERNAME_PASSWORD: 'REQUIRE_PHONE_USERNAME_PASSWORD',

  // --- Lỗi Đăng nhập & Xác thực (Bổ sung/Thay thế) ---
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS', // Đăng nhập sai
  AUTH_MISSING_FIELDS: 'AUTH_MISSING_FIELDS', // Thiếu trường trong request
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED', // Access token hết hạn
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN', // Access token không hợp lệ
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED', // khi email chưa đc verify

  // --- Lỗi logic xử lí 
  USER_HASH_FAILED: 'USER_HASH_FAILED',

  // --- Lỗi Người dùng & Ủy quyền (Bổ sung) ---
  AUTH_ACCESS_DENIED: 'AUTH_ACCESS_DENIED', // 403 Forbidden
  USER_INACTIVE: 'USER_INACTIVE',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED', // Lỗi xác thực dữ liệu
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',

  // --- Lỗi Chung (Bổ sung) ---
  SERVER_INTERNAL_ERROR: 'SERVER_INTERNAL_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  INVALID_INPUT: 'INVALID_INPUT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
};